/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author CARLOS
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menualumnos = new javax.swing.JMenu();
        menucursos = new javax.swing.JMenu();
        menuprofesores = new javax.swing.JMenu();
        menunotas = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jMenu4.setText("Inicio");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Mantenimiento");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        menualumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FELIZ.GIF"))); // NOI18N
        menualumnos.setText("Alumnos");
        menualumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menualumnosMouseClicked(evt);
            }
        });
        jMenu5.add(menualumnos);

        menucursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.jpg"))); // NOI18N
        menucursos.setText("Cursos");
        menucursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucursosMouseClicked(evt);
            }
        });
        jMenu5.add(menucursos);

        menuprofesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b_usrcheck.png"))); // NOI18N
        menuprofesores.setText("Profesores");
        menuprofesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuprofesoresMouseClicked(evt);
            }
        });
        jMenu5.add(menuprofesores);

        menunotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        menunotas.setText("Notas");
        menunotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menunotasMouseClicked(evt);
            }
        });
        jMenu5.add(menunotas);

        jMenuBar1.add(jMenu5);

        jMenu10.setText("Ayuda");

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clientes.jpg"))); // NOI18N
        jMenu13.setText("Manual");
        jMenu10.add(jMenu13);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material.gif"))); // NOI18N
        jMenu12.setText("Acerca de...");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenu10.add(jMenu12);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menualumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menualumnosMouseClicked
        // TODO add your handling code here:
        FRMAlumnos f=new FRMAlumnos();
        f.show();
    }//GEN-LAST:event_menualumnosMouseClicked

    private void menucursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucursosMouseClicked
        // TODO add your handling code here:
        FRMCursos f=new FRMCursos();
        f.show();
    }//GEN-LAST:event_menucursosMouseClicked

    private void menuprofesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuprofesoresMouseClicked
        // TODO add your handling code here:
        FRMProfesores f=new FRMProfesores();
        f.show();
    }//GEN-LAST:event_menuprofesoresMouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        // TODO add your handling code here:
        AcercaDe f=new AcercaDe();
        f.show();
    }//GEN-LAST:event_jMenu12MouseClicked

    private void menunotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menunotasMouseClicked
        // TODO add your handling code here:
        FRMNotas f=new FRMNotas();
        f.show();
    }//GEN-LAST:event_menunotasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menualumnos;
    private javax.swing.JMenu menucursos;
    private javax.swing.JMenu menunotas;
    private javax.swing.JMenu menuprofesores;
    // End of variables declaration//GEN-END:variables
}
